In [1]:
import pandas as pd
from pathlib import Path
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader, WeightedRandomSampler
import os
from PIL import Image
import matplotlib.pyplot as plt
from torchvision.transforms import v2
from torchvision import datasets, models, transforms, utils
from sklearn.metrics import classification_report
import numpy as np
from tqdm import tqdm

In [2]:
PROJECT_ROOT = Path().resolve().parent 
RAW_DATA_DIR = PROJECT_ROOT / "project4368" / "data"
CSV1_PATH = RAW_DATA_DIR / "Chest_xray_Corona_Metadata.csv"
CSV2_PATH = RAW_DATA_DIR / "Chest_xray_Corona_dataset_Summary.csv"
IMG_DIR_train = RAW_DATA_DIR / "Coronahack-Chest-XRay-Dataset" / "train"
IMG_DIR_test = RAW_DATA_DIR / "Coronahack-Chest-XRay-Dataset" / "test"

# Data overview

In [3]:
df = pd.read_csv(CSV1_PATH)
df.head()

,Unnamed: 0,X_ray_image_name,Label,Dataset_type,Label_2_Virus_category,Label_1_Virus_category
0,0,IM-0128-0001.jpeg,Normal,TRAIN,NaN,NaN
1,1,IM-0127-0001.jpeg,Normal,TRAIN,NaN,NaN
2,2,IM-0125-0001.jpeg,Normal,TRAIN,NaN,NaN
3,3,IM-0122-0001.jpeg,Normal,TRAIN,NaN,NaN
4,4,IM-0119-0001.jpeg,Normal,TRAIN,NaN,NaN

In [4]:
df_sum = pd.read_csv(CSV2_PATH)
df_sum

,Unnamed: 0,Label,Label_1_Virus_category,Label_2_Virus_category,Image_Count
0,0,Normal,NaN,NaN,1576
1,1,Pnemonia,Stress-Smoking,ARDS,2
2,2,Pnemonia,Virus,NaN,1493
3,3,Pnemonia,Virus,COVID-19,58
4,4,Pnemonia,Virus,SARS,4
5,5,Pnemonia,bacteria,NaN,2772
6,6,Pnemonia,bacteria,Streptococcus,5

In [5]:
print(df['Label'].value_counts())

Label
Pnemonia    4334
Normal      1576
Name: count, dtype: int64

In [6]:
print("Normal and label 1 virus:")
print(df[df['Label'] == "Normal"]['Label_1_Virus_category'].value_counts())
print("\nPnemonia and label 1 virus:")
print(df[df['Label'] == "Pnemonia"]['Label_1_Virus_category'].value_counts())

Normal and label 1 virus:
Series([], Name: count, dtype: int64)

Pnemonia and label 1 virus:
Label_1_Virus_category
bacteria          2777
Virus             1555
Stress-Smoking       2
Name: count, dtype: int64

In [7]:
mid_index = 5286
df_train = df.iloc[:mid_index]
df_test = df.iloc[mid_index:]

In [8]:
df_test.head()

,Unnamed: 0,X_ray_image_name,Label,Dataset_type,Label_2_Virus_category,Label_1_Virus_category
5286,5309,IM-0021-0001.jpeg,Normal,TEST,NaN,NaN
5287,5310,IM-0019-0001.jpeg,Normal,TEST,NaN,NaN
5288,5311,IM-0017-0001.jpeg,Normal,TEST,NaN,NaN
5289,5312,IM-0016-0001.jpeg,Normal,TEST,NaN,NaN
5290,5313,IM-0015-0001.jpeg,Normal,TEST,NaN,NaN

In [9]:
df_train.head()

,Unnamed: 0,X_ray_image_name,Label,Dataset_type,Label_2_Virus_category,Label_1_Virus_category
0,0,IM-0128-0001.jpeg,Normal,TRAIN,NaN,NaN
1,1,IM-0127-0001.jpeg,Normal,TRAIN,NaN,NaN
2,2,IM-0125-0001.jpeg,Normal,TRAIN,NaN,NaN
3,3,IM-0122-0001.jpeg,Normal,TRAIN,NaN,NaN
4,4,IM-0119-0001.jpeg,Normal,TRAIN,NaN,NaN

In [10]:
df_train['Label'].value_counts()

Label
Pnemonia    3944
Normal      1342
Name: count, dtype: int64

The dataset is imbalanced. Hence, we can use the custom random sampler to repeat the minority class or apply cross-entropy to reduce the impact of imbalance. In this case, we only implemented cross-entropy loss because the imbalance is mild. This approach is more efficient due to faster runtime and the same prediction. It is not necessary to implement both because it takes more time and may cause overfitting in the prediction.

In [11]:
class XRayDataset(Dataset):
    def __init__(self, dataframe, img_dir, transform=None):
        self.data = dataframe.reset_index(drop=True)  
        self.img_dir = img_dir
        self.transform = transform

        # Encode labels to integers
        self.label_encoder = {label: idx for idx, label in enumerate(self.data['Label'].unique())}
        self.data['Label_idx'] = self.data['Label'].map(self.label_encoder)
        self.classes = sorted(self.label_encoder, key=self.label_encoder.get)

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        img_name = self.data.iloc[idx]['X_ray_image_name']
        img_path = os.path.join(self.img_dir, img_name)
        label = self.data.iloc[idx]['Label_idx']

        try:
            image = Image.open(img_path).convert('L')  # Grayscale
        except:
            image = Image.new('L', (224, 224))

        image = self.transform(image)

        return image, label

In [12]:
train_transforms = v2.Compose([
    v2.Resize(256),
    v2.RandomResizedCrop((224, 224), antialias=True),
    v2.RandomAffine(degrees=(-10, 10), translate=(0.1, 0.1), scale=(0.9, 1.1)),
    v2.Grayscale(num_output_channels=1),  
    v2.PILToTensor(),
    v2.ToDtype(torch.float32),
    v2.Normalize(mean=[0.5], std=[0.5])
])

test_transforms = v2.Compose([
    v2.Resize((224,224)),
    v2.PILToTensor(),
    v2.ToDtype(torch.float32),
    v2.Normalize(mean=[0.5], std=[0.5])
])

In [13]:
# Load datasets
train_dataset = XRayDataset(dataframe=df_train, img_dir=IMG_DIR_train, transform=train_transforms)
test_dataset = XRayDataset(dataframe=df_test, img_dir=IMG_DIR_test, transform=test_transforms)

In [14]:
# DataLoaders
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [15]:
class modelCNN(nn.Module):
    def __init__(self):
        super(modelCNN, self).__init__()
        self.features = nn.Sequential(
            # First conv block
            nn.Conv2d(1, 32, kernel_size=3, padding=1),  # grayscale input: 1 channel
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Second conv block
            nn.Conv2d(32, 64, kernel_size=3, padding=1),
            nn.BatchNorm2d(64),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2),

            # Third conv block
            nn.Conv2d(64, 128, kernel_size=3, padding=1),
            nn.BatchNorm2d(128),
            nn.ReLU(inplace=True),
            nn.MaxPool2d(2)
        )

        # Global Average Pooling
        self.gap = nn.AdaptiveAvgPool2d((1, 1))  

        # Fully connected layers
        self.classifier = nn.Sequential(
            nn.Flatten(),  
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.Linear(128, 2),
        )

    def forward(self, x):
        x = self.features(x)
        x = self.gap(x)
        x = self.classifier(x)
        return x

In [16]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = modelCNN().to(device)

# Loss and optimizer
class_counts = [1500, 3500]
weights = [1.0 / count for count in class_counts]
weights = torch.FloatTensor(weights).to(device)
criterion = nn.CrossEntropyLoss(weight=weights)

optimizer = torch.optim.AdamW(model.parameters(), lr=1e-4)

lr_milestones = [7, 14, 21, 28, 35]
scheduler = torch.optim.lr_scheduler.MultiStepLR(optimizer, milestones=lr_milestones, gamma=0.1)

In [17]:
def train(dataloader, model, loss_fn, optimizer, lr_scheduler):
    size = len(dataloader.dataset) # number of samples
    num_batches = len(dataloader) # batches per epoch
    model.train()
    epoch_loss = 0.0
    epoch_correct = 0 
    for (data_,target_) in dataloader:
        target_ = target_.type(torch.LongTensor)
        data_, target_ = data_.to(device), target_.to(device)
        
        # First we'll clean the cache of optimizer
        optimizer.zero_grad()
        
        # Forward propagation
        outputs = model(data_)
        
        # Computing loss 
        loss = criterion(outputs,target_)
        
        # Backward propagation
        loss.backward()
        
        # Optimizing model
        optimizer.step()
        
        # Computing statistics.
        epoch_loss = epoch_loss + loss.item()
        _,pred = torch.max(outputs,dim=1)
        epoch_correct = epoch_correct + torch.sum(pred == target_).item()
    lr_scheduler.step()
    return epoch_correct/size, epoch_loss/num_batches


def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset) # number of samples
    num_batches = len(dataloader) # batches per epoch
    epoch_loss = 0.0
    epoch_correct = 0 
    with torch.no_grad():
        # Disable backward propagation
        model.eval()
        for (data_,target_) in dataloader:
            target_ = target_.type(torch.LongTensor)
            data_, target_ = data_.to(device), target_.to(device)

            # Forward propagation
            outputs = model(data_)
            
            # Computing loss 
            loss = criterion(outputs,target_)
            
            # Computing statistics.
            epoch_loss = epoch_loss + loss.item()
            _,pred = torch.max(outputs,dim=1)
            
            epoch_correct = epoch_correct + torch.sum(pred == target_).item()
    return  epoch_correct/size, epoch_loss/num_batches

In [18]:
EPOCHS = 30

storage = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

# Earlystopping
patience = 20
counter = 0
best_loss = np.inf

for epoch in tqdm(range(EPOCHS)):
    train_acc, train_loss,  = train(train_loader, model, criterion, optimizer, scheduler)
    val_acc, val_loss = test(test_loader, model, criterion)
    print(f'EPOCH: {epoch}, train_loss: {train_loss:.4f}, train_acc: {train_acc:.4f} val_loss: {val_loss:.4f}, val_acc: {val_acc:.4f}')
    
    storage['train_loss'].append(train_loss)
    storage['train_acc'].append(train_acc)
    storage['val_loss'].append(val_loss)
    storage['val_acc'].append(val_acc)
    torch.save(model.state_dict(), "last.pth")

    if val_loss < best_loss:
        counter = 0
        best_loss = val_loss
        torch.save(model.state_dict(), "best.pth")
    else:
        counter += 1
    if counter >= patience:
        print("Earlystop!")
        break

  3%|▎         | 1/30 [01:01<29:44, 61.54s/it]

EPOCH: 0, train_loss: 0.6169, train_acc: 0.7019 val_loss: 0.6430, val_acc: 0.6250

  7%|▋         | 2/30 [02:02<28:38, 61.38s/it]

EPOCH: 1, train_loss: 0.5104, train_acc: 0.7981 val_loss: 0.4638, val_acc: 0.8125

 10%|█         | 3/30 [03:04<27:34, 61.30s/it]

EPOCH: 2, train_loss: 0.4699, train_acc: 0.8123 val_loss: 0.8392, val_acc: 0.5016

 13%|█▎        | 4/30 [04:05<26:38, 61.48s/it]

EPOCH: 3, train_loss: 0.4161, train_acc: 0.8301 val_loss: 0.7203, val_acc: 0.6138

 17%|█▋        | 5/30 [05:07<25:39, 61.59s/it]

EPOCH: 4, train_loss: 0.4116, train_acc: 0.8348 val_loss: 0.4389, val_acc: 0.8061

 20%|██        | 6/30 [06:08<24:32, 61.34s/it]

EPOCH: 5, train_loss: 0.3912, train_acc: 0.8432 val_loss: 0.5261, val_acc: 0.7420

 23%|██▎       | 7/30 [07:08<23:24, 61.07s/it]

EPOCH: 6, train_loss: 0.3970, train_acc: 0.8428 val_loss: 0.5869, val_acc: 0.7083

 27%|██▋       | 8/30 [08:09<22:19, 60.90s/it]

EPOCH: 7, train_loss: 0.3735, train_acc: 0.8479 val_loss: 0.4338, val_acc: 0.8061

 30%|███       | 9/30 [09:09<21:15, 60.72s/it]

EPOCH: 8, train_loss: 0.3652, train_acc: 0.8500 val_loss: 0.4361, val_acc: 0.7933

 33%|███▎      | 10/30 [10:10<20:12, 60.64s/it]

EPOCH: 9, train_loss: 0.3668, train_acc: 0.8538 val_loss: 0.4407, val_acc: 0.7885

 37%|███▋      | 11/30 [11:10<19:07, 60.41s/it]

EPOCH: 10, train_loss: 0.3684, train_acc: 0.8534 val_loss: 0.4512, val_acc: 0.7981

 40%|████      | 12/30 [12:10<18:06, 60.35s/it]

EPOCH: 11, train_loss: 0.3716, train_acc: 0.8553 val_loss: 0.4504, val_acc: 0.7821

 43%|████▎     | 13/30 [13:10<17:04, 60.26s/it]

EPOCH: 12, train_loss: 0.3512, train_acc: 0.8619 val_loss: 0.4315, val_acc: 0.8013

 47%|████▋     | 14/30 [14:11<16:07, 60.47s/it]

EPOCH: 13, train_loss: 0.3601, train_acc: 0.8547 val_loss: 0.4333, val_acc: 0.8013

 50%|█████     | 15/30 [15:11<15:06, 60.46s/it]

EPOCH: 14, train_loss: 0.3475, train_acc: 0.8608 val_loss: 0.4309, val_acc: 0.8045

 53%|█████▎    | 16/30 [16:12<14:05, 60.41s/it]

EPOCH: 15, train_loss: 0.3536, train_acc: 0.8562 val_loss: 0.4346, val_acc: 0.8077

 57%|█████▋    | 17/30 [17:13<13:07, 60.57s/it]

EPOCH: 16, train_loss: 0.3681, train_acc: 0.8488 val_loss: 0.4348, val_acc: 0.8045

 60%|██████    | 18/30 [18:15<12:13, 61.13s/it]

EPOCH: 17, train_loss: 0.3543, train_acc: 0.8604 val_loss: 0.4320, val_acc: 0.8029

 63%|██████▎   | 19/30 [19:16<11:11, 61.00s/it]

EPOCH: 18, train_loss: 0.3655, train_acc: 0.8594 val_loss: 0.4384, val_acc: 0.8093

 67%|██████▋   | 20/30 [20:42<11:26, 68.60s/it]

EPOCH: 19, train_loss: 0.3567, train_acc: 0.8602 val_loss: 0.4336, val_acc: 0.8045

 70%|███████   | 21/30 [22:19<11:33, 77.07s/it]

EPOCH: 20, train_loss: 0.3518, train_acc: 0.8575 val_loss: 0.4284, val_acc: 0.8013

 73%|███████▎  | 22/30 [23:19<09:36, 72.03s/it]

EPOCH: 21, train_loss: 0.3527, train_acc: 0.8564 val_loss: 0.4311, val_acc: 0.8029

 77%|███████▋  | 23/30 [24:21<08:03, 69.04s/it]

EPOCH: 22, train_loss: 0.3610, train_acc: 0.8515 val_loss: 0.4387, val_acc: 0.8061

 80%|████████  | 24/30 [25:22<06:38, 66.45s/it]

EPOCH: 23, train_loss: 0.3594, train_acc: 0.8579 val_loss: 0.4301, val_acc: 0.8029

 83%|████████▎ | 25/30 [26:22<05:23, 64.72s/it]

EPOCH: 24, train_loss: 0.3545, train_acc: 0.8560 val_loss: 0.4355, val_acc: 0.8093

 87%|████████▋ | 26/30 [27:23<04:13, 63.44s/it]

EPOCH: 25, train_loss: 0.3545, train_acc: 0.8606 val_loss: 0.4285, val_acc: 0.8013

 90%|█████████ | 27/30 [28:24<03:08, 62.80s/it]

EPOCH: 26, train_loss: 0.3522, train_acc: 0.8579 val_loss: 0.4310, val_acc: 0.8045

 93%|█████████▎| 28/30 [29:24<02:04, 62.10s/it]

EPOCH: 27, train_loss: 0.3633, train_acc: 0.8528 val_loss: 0.4337, val_acc: 0.8061

 97%|█████████▋| 29/30 [30:25<01:01, 61.62s/it]

EPOCH: 28, train_loss: 0.3568, train_acc: 0.8579 val_loss: 0.4347, val_acc: 0.8077

100%|██████████| 30/30 [31:25<00:00, 62.85s/it]

EPOCH: 29, train_loss: 0.3556, train_acc: 0.8602 val_loss: 0.4293, val_acc: 0.8013

In [19]:
from sklearn.metrics import classification_report

# Get best model
model.load_state_dict(torch.load("best.pth"))          
model.eval()

all_preds = []
all_labels = []

with torch.no_grad():
    for images, labels in test_loader:                
        images = images.to(device)                    
        # Get true target value
        labels = labels.to(device)

        # Get prediction
        outputs = model(images)
        preds = torch.argmax(outputs, dim=1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())


# Classification report
target_names = ["Normal", "Pnemonia"]
print(classification_report(all_labels, all_preds, target_names=target_names))

              precision    recall  f1-score   support

           0       0.75      0.70      0.72       234
           1       0.83      0.86      0.84       390

    accuracy                           0.80       624
   macro avg       0.79      0.78      0.78       624
weighted avg       0.80      0.80      0.80       624

In [ ]:
from sklearn.metrics confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# Confusion matrix
cm = confusion_matrix(all_labels, all_preds)

plt.figure(figsize=(6, 5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names,
            yticklabels=target_names)
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.title("Confusion Matrix")
plt.tight_layout()
plt.show()